name: test

defaults:
  run:
    shell: bash -ex {0}

permissions:
  contents: write

on:
  push:
    branches: [ main ]
    paths-ignore:
      - README.md
  pull_request:
    branches: [ main ]
    paths-ignore:
      - README.md

jobs:
  render:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install jupyter nbformat nbclient matplotlib pyyaml

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install LaTeX and rsvg (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-luatex librsvg2-bin biber texlive-bibtex-extra texlive-latex-recommended texlive-latex-extra texlive-lang-polish

      - name: Install LaTeX and rsvg (macOS)
        if: runner.os == 'macOS'
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          quarto install tinytex --no-prompt --update-path
          brew install librsvg

      - name: Install LaTeX & rsvg and point Quarto to correct Python (Windows)
        if: runner.os == 'Windows'
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          quarto install tinytex --no-prompt --update-path
          choco install rsvg-convert -y
          echo "QUARTO_PYTHON=python" >> $GITHUB_ENV

      - name: Test template installation
        run: |
          mkdir test-project 
          cd test-project
          quarto use template .. --no-prompt

      - name: Render example notebook to PDF
        run: |
          echo $QUARTO_PYTHON
          quarto render test-project/thesis.ipynb 

      - name: Rename PDF (platform-specific)
        run: | 
          mv test-project/thesis.pdf example-${{ matrix.os }}.pdf 

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v7
        with: 
          name: pdf-${{ matrix.os }}
          path: example-${{ matrix.os }}.pdf

      - name: Upload a GIF version for inclusion in README
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install imagemagick
          convert -density 100 example-${{ matrix.os }}.pdf -quality 100 -background white -alpha remove -alpha off frame-%03d.png
          mkdir -p $HOME/work/_temp/_github_home/
          convert -delay 120 -loop 0 frame-*.png $HOME/work/_temp/_github_home/thesis.gif
          cp example-${{ matrix.os }}.pdf $HOME/work/_temp/_github_home/thesis.pdf

      - name: tip release upload
        if: github.ref == 'refs/heads/main' && runner.os == 'Linux'
        uses: eine/tip@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: /github/home/thesis.*

  check-quarto-no-args:
    runs-on: ubuntu-latest
    env:
      PDF_FILENAME: "thesis.pdf"
    steps:
      - use: quarto-dev/quarto-actions/setup@v2
      - use: actions/checkout@v6
      - run: pip install -r requirements.txt
      - run: quarto render
      - run: test -f $PDF_FILENAME
