name: test

defaults:
  run:
    shell: bash -ex {0}

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  render:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest] #, macos-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install jupyter nbformat nbclient matplotlib pyyaml

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install LaTeX and rsvg (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-luatex librsvg2-bin biber texlive-bibtex-extra texlive-latex-recommended texlive-latex-extra texlive-lang-polish

      - name: Install LaTeX and rsvg (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install texlive librsvg

      - name: Install LaTeX & rsvg and point Quarto to correct Python (Windows)
        if: runner.os == 'Windows'
        run: |
          quarto install tinytex --no-prompt --update-path
          choco install rsvg-convert -y
          echo "QUARTO_PYTHON=python" >> $GITHUB_ENV

      - name: Test template installation
        run: |
          mkdir test-project 
          cd test-project
          quarto use template .. --no-prompt

      - name: Render example notebook to PDF
        run: |
          echo $QUARTO_PYTHON
          quarto render test-project/thesis.ipynb 

      - name: Rename PDF (platform-specific)
        run: | 
          mv test-project/thesis.pdf example-${{ matrix.os }}.pdf 

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v7
        with: 
          name: pdf-${{ matrix.os }}
          path: example-${{ matrix.os }}.pdf
